# Generated by Django 4.2.11 on 2024-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="initiated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="request",
            name="pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="request",
            name="id_number",
            field=models.CharField(max_length=100),
        ),
    ]
