# Generated by Django 4.2.11 on 2024-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_request_initiated_request_pending_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="request", name="description",),
        migrations.RemoveField(model_name="request", name="initiated",),
        migrations.RemoveField(model_name="request", name="pending",),
        migrations.AddField(
            model_name="request",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
    ]
